Add an include so this builds on OS X
Avoids these compile messages:

In file included from /Users/jgoggins/git/particle/geofence/src/Geofence.cpp:17:
/Users/jgoggins/git/particle/geofence/src/Geofence.h:199:23: error: call to 'abs' is ambiguous
        _maximumDop = abs(dop);
                      ^~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:111:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:113:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
1 error generated.
make[2]: *** [CMakeFiles/geofence-test.dir/src/Geofence.cpp.o] Error 1
make[1]: *** [CMakeFiles/geofence-test.dir/all] Error 2
make: *** [all] Error 2